### PR TITLE
Remove need for findIndex polyfill, change to findIndex

### LINKED ISSUE #237: "TypeError: Object doesn't support property or method 'findIndex' IE 11
Latest version 3.0.0
IE 11 version
I gues error here:

` public readonly isItemExpanded = (uuid: UUID): boolean => {
        return (
            this.expanded.findIndex(
                (expandedUuid: UUID) => expandedUuid === uuid,
            ) !== -1
        );
    };`

### PR DESCRIPTION
**Pull request by janzenz**
Closes #237 #244. Adding clarification for people who are seeing error `Array.prototype.findIndex` on IE 11.

### CODE REVIEW

**Comment by YoavHortman** [comment]
Maybe also adding to the readme in the browser support section:
IE 11 (Reqruies polyfill [link to polyfill](url)

**Comment by janzenz** [comment]
@liamjohnston I was actually thinking about that but I thought I'd let the people be creative and search the term on Google coz chances are that link might get stale, no?

**Comment by ryami333** [comment]
Thanks for this @janzenz, as a matter of fact though: we do support IE11 [explicitly](https://github.com/springload/react-accessible-accordion#browser-support) so this is actually a bug (ie. we need to refactor away uses of `findIndex` for something that is Ie11 compatible). Is this something you wouldn't mind looking into?

**Comment by ryami333** [comment]
Think there's only one, and it looks like it can basically be a straight swap for `indexOf`

**Comment by liamjohnston** [comment]
Watching this issue so I can remove the polyfill from "that banking website".

**Comment by janzenz** [comment]
@ryami333 do we? I actually thought we explicitly didn't support `findIndex` so that we leave the polyfill to the users to include. Which I think is good so people won't end up having duplicate `findIndex` polyfills in their bundle.

**Comment by ryami333** [comment]
Yeah I'm not suggesting including the polyfill - just using a different (IE11-supported) array-method (`.indexOf`) instead, so that no poyfills are even needed :)

**Comment by liamjohnston** [comment]
@janzenz Mitch is saying you can swap `findIndex` with `indexOf` then no one needs the polyfill.

**Comment by ryami333** [comment]
Jinx @liamjohnston !

**Comment by janzenz** [comment]
@ryami333 seems that coveralls seems not happy. I guess it's because we've dropped 4 lines of code. Is there a way to skip this check? The file changed has 100% coverage already and I don't think adding more test on unrelated files should be part of this PR. What do you think?

**Pull request merged**
